### ISSUE TITLE
itemsPerPage is not translated

### ISSUE THREAD

**Issue by majsterka** [loudenvier/kendo-global#42]
Hello, 
I`m using  my own file, I have there 
kendo.ui.Pager.prototype.options.messages =
  $.extend(kendo.ui.Pager.prototype.options.messages, {
....
itemsPerPage: "položiek na stránku",
.....

but this only one item is not translated.
Can you give me a suggestion where should be a problem?
I`m using kendo 2013.2.716

**Comment by Vohuman** [comment]
It doesn't work for me too on version 2017
